name: Watch JSON Files in "WOT/" Directory
on:
  push:
    paths:
      - 'FoxESS_inverter/**/*.json'  # Runs when any JSON file inside "thing/" is added or modified
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  update-ditto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch last 2 commits to compare changes

      - name: Identify Changed JSON Files
        id: changed_files
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '^FoxESS_inverter/.*\.json$' || echo "")
          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "Changed JSON files: $FILES"

      - name: Check if Any JSON Files Were Changed
        if: env.FILES == ''
        run: echo "No JSON file changes detected. Skipping workflow."

      - name: Extract Repository Information
        run: |
          echo "ORG_NAME=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Identify Changed JSON Files
        run: |
          FILE_PATHS=$(git diff --name-only HEAD~1 HEAD | grep 'FoxESS_inverter/.*\.json$' || echo "")
          echo "CHANGED_FILES=$FILE_PATHS" >> $GITHUB_ENV
          echo "Modified Files: $FILE_PATHS"
          
      - name: Fetch Private Raw File URL
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            for FILE in $CHANGED_FILES; do
              API_URL="https://api.github.com/repos/$ORG_NAME/$REPO_NAME/contents/$FILE?ref=$BRANCH_NAME"
              RAW_URL=$(curl -s -H "Authorization: token $GH_TOKEN" "$API_URL" | jq -r '.download_url')
              echo "Private Raw URL for $FILE: $RAW_URL"
              echo "RAW_FILE_URL=$RAW_URL" >> $GITHUB_ENV
            done
          else
            echo "No modified JSON files found."
          fi

      - name: Display Generated URL
        run: |
          echo "✅ Download the private file from: $RAW_FILE_URL"
