name: Generate Private Raw GitHub File URL

on:
  push:
    paths:
      - 'FoxESS_inverter/**'  # Trigger when any file in this directory is modified
  workflow_dispatch:  # Allows manual execution

jobs:
  generate-private-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set Variables
        run: |
          echo "ORG_NAME=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "FILE_PATH=$(git diff --name-only HEAD~1 HEAD | grep 'FoxESS_inverter/' || echo '')" >> $GITHUB_ENV

      - name: Generate Private GitHub API URL
        run: |
          if [ -n "$FILE_PATH" ]; then
            API_URL="https://api.github.com/repos/$ORG_NAME/$REPO_NAME/contents/$FILE_PATH?ref=$BRANCH_NAME"
            AUTH_HEADER="Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}"
            echo "API_URL=$API_URL" >> $GITHUB_ENV
          else
            echo "No matching files changed in the FoxESS_inverter directory."
          fi

      - name: Fetch Raw File URL
        run: |
          if [ -n "$API_URL" ]; then
            RAW_URL=$(curl -s -H "$AUTH_HEADER" "$API_URL" | jq -r '.download_url')
            echo "Generated Private Raw URL: $RAW_URL"
            echo "RAW_FILE_URL=$RAW_URL" >> $GITHUB_ENV
          fi

      - name: Output Raw URL
        run: |
          echo "Download the private file from: $RAW_FILE_URL"
