name: Generate Raw GitHub File URL

on:
  push:
    paths:
      - 'FoxESS_inverter/**'  # Triggers when any file inside FoxESS_inverter/ is modified
  workflow_dispatch:  # Allows manual execution

jobs:
  generate-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set Variables
        run: |
          echo "ORG_NAME=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "BRANCH_NAME=refs/heads/${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "FILE_PATH=$(git diff --name-only HEAD~1 HEAD | grep 'FoxESS_inverter/' || echo '')" >> $GITHUB_ENV

      - name: Generate Raw GitHub URL
        run: |
          if [ -n "$FILE_PATH" ]; then
            RAW_URL="https://raw.githubusercontent.com/$ORG_NAME/$REPO_NAME/$BRANCH_NAME/$FILE_PATH"
            echo "Generated Raw URL: $RAW_URL"
            echo "RAW_FILE_URL=$RAW_URL" >> $GITHUB_ENV
          else
            echo "No matching files changed in the FoxESS_inverter directory."
          fi

      - name: Output Raw URL
        run: |
          echo "Download the file from: $RAW_FILE_URL"
