name: Watch JSON Files in "WOT/" Directory
on:
  push:
    paths:
      - 'FoxESS_inverter/**/*.json'  # Runs when any JSON file inside "thing/" is added or modified
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  update-ditto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch last 2 commits to compare changes

      - name: Identify Changed JSON Files
        id: changed_files
        run: |
          FILES=$(git diff --name-only HEAD~1 HEAD | grep '^FoxESS_inverter/.*\.json$' || echo "")
          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "Changed JSON files: $FILES"

      - name: Check if Any JSON Files Were Changed
        if: env.FILES == ''
        run: echo "No JSON file changes detected. Skipping workflow."
