name: Rewrite submodel URLs with signed GitHub links

on:
  workflow_dispatch:  # Manual trigger (you can also use push event)

jobs:
  rewrite-submodels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Rewrite submodel URLs in masterthing.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}  # e.g. my-org/my-private-repo
          BRANCH: ${{ github.ref_name }}  # e.g. main
        run: |
          ORG_NAME=$(echo "$REPO" | cut -d/ -f1)
          REPO_NAME=$(echo "$REPO" | cut -d/ -f2)
          FILE=FoxESS_inverter/fieldthing.json

          echo "🔍 Processing $FILE for submodel links..."

          # Get all hrefs in the links array
          HREFS=$(jq -r '.links[].href' "$FILE")

          for HREF in $HREFS; do
            echo "➡️ Found href: $HREF"

            # Extract relative file path from GitHub-style URL
            FILE_PATH=$(echo "$HREF" | sed -E "s|https://github.com/$ORG_NAME/$REPO_NAME/blob/$BRANCH/||")

            echo "📁 Resolved submodel path: $FILE_PATH"

            # Call GitHub API to get download_url
            API_URL="https://api.github.com/repos/$ORG_NAME/$REPO_NAME/contents/$FILE_PATH?ref=$BRANCH"
            DOWNLOAD_URL=$(curl -s -H "Authorization: token $GH_PAT" "$API_URL" | jq -r '.download_url')

            if [[ "$DOWNLOAD_URL" == "null" || -z "$DOWNLOAD_URL" ]]; then
              echo "❌ Failed to resolve signed URL for $FILE_PATH"
              exit 1
            fi

            echo "✅ Signed URL: $DOWNLOAD_URL"
            # Replace the href in the file
            sed -i "s|$HREF|$DOWNLOAD_URL|g" "$FILE"
          done

          echo "✅ Updated $FILE with signed submodel URLs:"
          cat "$FILE"
