name: Rewrite Submodel URLs in fieldthing.json

on:
  push:
    paths:
      - 'FoxESS_inverter/fieldthing.json'

jobs:
  rewrite-submodels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Rewrite submodel URLs in fieldthing.json
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}  # e.g. org/repo
          BRANCH: ${{ github.ref_name }}  # e.g. main
        run: |
          ORG_NAME=$(echo "$REPO" | cut -d/ -f1)
          REPO_NAME=$(echo "$REPO" | cut -d/ -f2)
          FILE=FoxESS_inverter/fieldthing.json

          echo "🔍 Processing $FILE for submodel links..."

          # Get all hrefs in the links array
          HREFS=$(jq -r '.links[].href' "$FILE")

          for HREF in $HREFS; do
            echo "➡️ Found href: $HREF"

            # Skip already signed raw URLs
            if [[ "$HREF" == https://raw.githubusercontent.com* ]]; then
              echo "🔁 Skipping already-signed raw URL: $HREF"
              continue
            fi

            # Extract path from GitHub blob URL
            FILE_PATH=$(echo "$HREF" | sed -E "s|https://github.com/$ORG_NAME/$REPO_NAME/blob/$BRANCH/||")

            if [[ -z "$FILE_PATH" || "$FILE_PATH" == "$HREF" ]]; then
              echo "⚠️ Unable to extract submodel path from $HREF — skipping"
              continue
            fi

            echo "📁 Resolved GitHub path: $FILE_PATH"

            # Use GitHub API to get signed raw download_url
            API_URL="https://api.github.com/repos/$ORG_NAME/$REPO_NAME/contents/$FILE_PATH?ref=$BRANCH"
            DOWNLOAD_URL=$(curl -s -H "Authorization: token $GH_PAT" "$API_URL" | jq -r '.download_url')

            if [[ "$DOWNLOAD_URL" == "null" || -z "$DOWNLOAD_URL" ]]; then
              echo "❌ Could not resolve download_url for $FILE_PATH"
              exit 1
            fi

            echo "✅ Replacing $HREF with signed URL: $DOWNLOAD_URL"
            sed -i "s|$HREF|$DOWNLOAD_URL|g" "$FILE"
          done

          echo "✅ Final updated $FILE:"
          cat "$FILE"
